### ISSUE TITLE
code and dataset

### ISSUE THREAD

**Issue by SiQube** [kishanmaharaj/gaze-hallucination-detection#1]
Dear authors,

as promised in your super interesting paper I'm looking for the code. Do you know when it will be released?

**Comment by kishanmaharaj** [comment]
Hii @SiQube, 
Thank you so much for expressing your interest in our work.

We anticipate providing the code in this repository within the next 2-3 weeks. 
We are currently figuring out the licensing aspect of the data; we will release the data as soon as possible.

**Comment by SiQube** [comment]
Hi @kishanmaharaj 

just wanted to checkin about the data and code -- any updates?

**Comment by kishanmaharaj** [comment]
Hi @SiQube, 
We have updated the repo with about 70% of the code. You can look at the folders: 1) Global Attention Bias and 2) Local Attention Bias. We will add a more comprehensive readme soon for better code navigation. We will soon add an example notebook to better understand the code flow and how to use the modules.

The data will be made public before the end of FEB 2024.

**Comment by SiQube** [comment]
thank you for the update, great that everything worked out with the data. looking forward to playing around with the data and the model.

**Comment by dongsenzhang** [comment]
Dear authors,

Is the dataset available now? I didn't find the dataset in huggingface.

**Comment by ashitas96** [comment]
The dataset can be found here: https://huggingface.co/datasets/cfilt/IITB-HGC 
We are trying to add more gaze related information like saccdes, pupil dilation in the data.

**Comment by dongsenzhang** [comment]
Thank you for building the dataset.

**Comment by SiQube** [comment]
Thank you
