### ISSUE TITLE
Model Weights or Training scripts

### ISSUE THREAD

**Issue by samuki** [kishanmaharaj/gaze-hallucination-detection#4]
Hi, thanks so much for sharing the code and the dataset!
Would it be possible to upload the weights of your final model (BERT+GAB+LAB+GAZE) or the training scripts to reproduce the model?

**Comment by kishanmaharaj** [comment]
Hi @samuki, sure...
We will try to share both of the above. You can expect the same by this week.

**Comment by samuki** [comment]
Great, thank you!
